version: "3"
services:
  server:
    container_name: iot-raspi-sensors-server
    image: ghcr.io/mmontes11/iot-raspi-sensors-server:v0.0.1
    env_file: .env
    hostname: ${HOSTNAME}
    network_mode: host
    dns: 100.100.100.100
    privileged: true
    restart: unless-stopped
  sensors:
    container_name: iot-raspi-sensors
    image: ghcr.io/mmontes11/iot-raspi-sensors:v0.0.2
    env_file: .env
    hostname: ${HOSTNAME}
    network_mode: host
    dns: 100.100.100.100
    privileged: true
    restart: unless-stopped
