version: "3"
services:
  server:
    container_name: iot-raspi-sensors-server
    image: mmontes11/iot-raspi-sensors-server:v0.0.1
    env_file: .env
    hostname: ${HOSTNAME}
    ports:
      - "${IOT_RASPI_NODE_PORT}:${IOT_RASPI_NODE_PORT}"
    privileged: true
    restart: unless-stopped
  sensors:
    container_name: iot-raspi-sensors
    image: mmontes11/iot-raspi-sensors:v0.0.1
    depends_on:
      - server
    env_file: .env
    hostname: ${HOSTNAME}
    privileged: true
    restart: unless-stopped

